; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
src_dir = .
lib_dir = ../..
boards_dir = ../../platformio/boards
default_envs = t4-4-7

[env]
platform = espressif32@6.3.0
upload_protocol = esptool
framework = arduino
upload_speed = 921600
monitor_speed = 115200
lib_deps = Wire, bblanchon/ArduinoJson@^6.21.0

[env:t4-4-7]
board = lilygo-t4-47
; upload_port = COMx
build_flags = -D CORE_DEBUG_LEVEL=3
